name: Linters

on:
  push:
    paths-ignore:
      - 'resources/**'
      - 'downloads/**'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - 'resources/**'
      - 'downloads/**'
    branches:
      - '**'

jobs:
  test:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "src"
          use-flake8: true
          extra-flake8-options: "--max-line-length=88"