name: Linters

on:
  push:
    paths-ignore:
      - 'resources/**'
      - 'downloads/**'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - 'resources/**'
      - 'downloads/**'
    branches:
      - '**'

jobs:
  test:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "88"
          path: "src"
